# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GtGUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!



from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(804, 435)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MotorController = QtWidgets.QGroupBox(self.centralwidget)
        self.MotorController.setGeometry(QtCore.QRect(20, 20, 201, 141))
        self.MotorController.setAutoFillBackground(True)
        self.MotorController.setObjectName("MotorController")
        self.label_2 = QtWidgets.QLabel(self.MotorController)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.MotorController)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 55, 16))
        self.label_3.setObjectName("label_3")
        self.voltsOutput = QtWidgets.QLabel(self.MotorController)
        self.voltsOutput.setGeometry(QtCore.QRect(100, 40, 55, 16))
        self.voltsOutput.setFrameShape(QtWidgets.QFrame.Box)
        self.voltsOutput.setText("")
        self.voltsOutput.setObjectName("voltsOutput")
        self.ampsOutput = QtWidgets.QLabel(self.MotorController)
        self.ampsOutput.setGeometry(QtCore.QRect(100, 90, 55, 16))
        self.ampsOutput.setFrameShape(QtWidgets.QFrame.Box)
        self.ampsOutput.setText("")
        self.ampsOutput.setObjectName("ampsOutput")
        self.powerStatsGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.powerStatsGroupBox.setGeometry(QtCore.QRect(250, 20, 231, 141))
        self.powerStatsGroupBox.setAutoFillBackground(True)
        self.powerStatsGroupBox.setObjectName("powerStatsGroupBox")
        self.label = QtWidgets.QLabel(self.powerStatsGroupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 55, 16))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.powerStatsGroupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 55, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.powerStatsGroupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 71, 16))
        self.label_5.setObjectName("label_5")
        self.mphOutput = QtWidgets.QLabel(self.powerStatsGroupBox)
        self.mphOutput.setGeometry(QtCore.QRect(120, 20, 55, 16))
        self.mphOutput.setFrameShape(QtWidgets.QFrame.Box)
        self.mphOutput.setText("")
        self.mphOutput.setObjectName("mphOutput")
        self.rpmOutput = QtWidgets.QLabel(self.powerStatsGroupBox)
        self.rpmOutput.setGeometry(QtCore.QRect(120, 60, 55, 16))
        self.rpmOutput.setFrameShape(QtWidgets.QFrame.Box)
        self.rpmOutput.setText("")
        self.rpmOutput.setObjectName("rpmOutput")
        self.odometerOutput = QtWidgets.QLabel(self.powerStatsGroupBox)
        self.odometerOutput.setGeometry(QtCore.QRect(120, 100, 55, 16))
        self.odometerOutput.setFrameShape(QtWidgets.QFrame.Box)
        self.odometerOutput.setText("")
        self.odometerOutput.setObjectName("odometerOutput")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(500, 20, 231, 141))
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setObjectName("groupBox")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 30, 55, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 70, 55, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(20, 110, 55, 16))
        self.label_8.setObjectName("label_8")
        self.acAmpsOutput = QtWidgets.QLabel(self.groupBox)
        self.acAmpsOutput.setGeometry(QtCore.QRect(120, 30, 55, 16))
        self.acAmpsOutput.setFrameShape(QtWidgets.QFrame.Box)
        self.acAmpsOutput.setText("")
        self.acAmpsOutput.setObjectName("acAmpsOutput")
        self.dcAmpsOutput = QtWidgets.QLabel(self.groupBox)
        self.dcAmpsOutput.setGeometry(QtCore.QRect(120, 70, 55, 16))
        self.dcAmpsOutput.setFrameShape(QtWidgets.QFrame.Box)
        self.dcAmpsOutput.setText("")
        self.dcAmpsOutput.setObjectName("dcAmpsOutput")
        self.rpmDcOutput = QtWidgets.QLabel(self.groupBox)
        self.rpmDcOutput.setGeometry(QtCore.QRect(120, 110, 55, 16))
        self.rpmDcOutput.setFrameShape(QtWidgets.QFrame.Box)
        self.rpmDcOutput.setText("")
        self.rpmDcOutput.setObjectName("rpmDcOutput")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(250, 180, 231, 101))
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(20, 40, 101, 16))
        self.label_9.setObjectName("label_9")
        self.powerTrackersOutput = QtWidgets.QLabel(self.groupBox_2)
        self.powerTrackersOutput.setGeometry(QtCore.QRect(140, 40, 55, 16))
        self.powerTrackersOutput.setFrameShape(QtWidgets.QFrame.Box)
        self.powerTrackersOutput.setText("")
        self.powerTrackersOutput.setObjectName("powerTrackersOutput")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 170, 211, 181))
        self.groupBox_3.setAutoFillBackground(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 30, 91, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(10, 110, 55, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(10, 150, 55, 16))
        self.label_13.setObjectName("label_13")
        self.packCurrentOutput = QtWidgets.QLabel(self.groupBox_3)
        self.packCurrentOutput.setGeometry(QtCore.QRect(120, 30, 55, 16))
        self.packCurrentOutput.setFrameShape(QtWidgets.QFrame.Box)
        self.packCurrentOutput.setText("")
        self.packCurrentOutput.setObjectName("packCurrentOutput")
        self.packVoltageOutput = QtWidgets.QLabel(self.groupBox_3)
        self.packVoltageOutput.setGeometry(QtCore.QRect(120, 70, 55, 16))
        self.packVoltageOutput.setFrameShape(QtWidgets.QFrame.Box)
        self.packVoltageOutput.setText("")
        self.packVoltageOutput.setObjectName("packVoltageOutput")
        self.socOutput = QtWidgets.QLabel(self.groupBox_3)
        self.socOutput.setGeometry(QtCore.QRect(120, 110, 55, 16))
        self.socOutput.setFrameShape(QtWidgets.QFrame.Box)
        self.socOutput.setText("")
        self.socOutput.setObjectName("socOutput")
        self.relayOutput = QtWidgets.QLabel(self.groupBox_3)
        self.relayOutput.setGeometry(QtCore.QRect(120, 150, 55, 16))
        self.relayOutput.setFrameShape(QtWidgets.QFrame.Box)
        self.relayOutput.setText("")
        self.relayOutput.setObjectName("relayOutput")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 804, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.MotorController.setTitle(_translate("MainWindow", "Motor Controller"))
        self.label_2.setText(_translate("MainWindow", "Volts"))
        self.label_3.setText(_translate("MainWindow", "Amps"))
        self.powerStatsGroupBox.setTitle(_translate("MainWindow", "Speed"))
        self.label.setText(_translate("MainWindow", "MPH"))
        self.label_4.setText(_translate("MainWindow", "RPM"))
        self.label_5.setText(_translate("MainWindow", "Odometer"))
        self.groupBox.setTitle(_translate("MainWindow", "Drive Command "))
        self.label_6.setText(_translate("MainWindow", "acAmps"))
        self.label_7.setText(_translate("MainWindow", "dcAmps"))
        self.label_8.setText(_translate("MainWindow", "rpmDc"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Power Trackers"))
        self.label_9.setText(_translate("MainWindow", "Power Trackers"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Pack Info"))
        self.label_10.setText(_translate("MainWindow", "Pack Current"))
        self.label_11.setText(_translate("MainWindow", "Pack Voltage"))
        self.label_12.setText(_translate("MainWindow", "Soc"))
        self.label_13.setText(_translate("MainWindow", "Relay"))

